import { useState, type Dispatch, type SetStateAction } from 'react';
import type { ScoreResult } from './types';
import { PATHS, RARITIES, SHOP, advanceExpedition, buyGear, gearPower, heroAttack, improveGear, improvePassive, improveSkill, levelOf, maxHealth, passivePoints, sellGear, skillCost, tierOf, upgradeCost, xpForLevel, type Gear, type Progress } from './questModel';

export function GearBadge({gear}:{gear?:Gear}) {
  return <span className={`ember-gear-icon tier-${tierOf(gear?.upgrade||0)}`} style={{color:RARITIES.find(r=>r.id===gear?.rarity)?.color}}>{gear?.slot==='armor'?'◈':PATHS.find(c=>c.id===gear?.affinity)?.icon||'⚔'}{gear&&gear.upgrade>=5&&<i>{'★'.repeat(Math.floor(gear.upgrade/5))}</i>}</span>;
}
export default function EmberCamp({progress:p,score,atCamp,onChange,onClose}:{progress:Progress;score:ScoreResult;atCamp:boolean;onChange:Dispatch<SetStateAction<Progress>>;onClose:()=>void}) {
  const [tab,setTab]=useState<'gear'|'skills'|'shop'|'rates'>('gear');
  const [rates,setRates]=useState(()=>({equipment:p.rates.equipment,weights:[...p.rates.weights]}));
  const [rateSaved,setRateSaved]=useState(false);
  const level=levelOf(p.xp),points=passivePoints(p),path=PATHS.find(c=>c.id===p.path)!;
  const total=rates.weights.reduce((a,b)=>a+b,0);
  return <div className="ember-modal-wrap ember-camp-wrap"><section className="ember-camp" role="dialog" aria-modal="true" aria-label="กระเป๋าและพัฒนาตัวละคร">
    <header className="ember-camp-heading"><div><small>THE WARMHEARTH CAMP</small><h2>เตรียมพร้อมก่อนเดินทาง</h2></div><button onClick={onClose} aria-label="ปิดกระเป๋า">×</button></header>
    <div className="ember-wallet"><span>◎ <b>{p.gold}</b> เหรียญ</span><span>◆ <b>{p.stones}</b> หินเวท</span><span>✧ <b>{p.essence}</b> ผลึกสกิล</span><span className={`ember-level tier-${tierOf(level)}`}>LV.{level}{level===20?' ★ MAX':' / 20'}</span></div>
    <div className="ember-camp-summary"><span style={{color:path.color}}>{path.icon} {path.role} · โจมตี {heroAttack(score,p)} · HP {maxHealth(score,p)}</span><span>{level===20?'ถึงขีดสุดแล้ว':`${p.xp-xpForLevel(level)} / ${xpForLevel(level+1)-xpForLevel(level)} XP`}</span></div>
    <nav className="ember-camp-tabs" aria-label="หมวดพัฒนาตัวละคร">{([['gear','◈ อุปกรณ์'],['skills','✦ สาย / สกิล'],['shop','◎ ร้านค้า'],['rates','⚙ เรตดรอป']] as const).map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    <div className="ember-camp-content">
      {tab==='gear'&&<><div className="ember-panel-note"><b>คลังอุปกรณ์ {p.inventory.length} / 40</b><span>{atCamp?'ตีบวกด้วยเงินและหินเวท สำเร็จ 100% สูงสุด +20':'สวมใส่และขายได้ทุกที่ · กลับแคมป์เพื่อตีบวก'}</span></div><div className="ember-tier-legend"><span className="tier-wood">+5 ไม้</span><span className="tier-red">+10 แดง</span><span className="tier-violet">+15 ม่วง</span><span className="tier-gold">+20 ทอง ★</span></div>
        <div className="ember-gear-grid">{p.inventory.map(gear=>{const wearing=p[gear.slot]===gear.id,cost=upgradeCost(gear),rarity=RARITIES.find(r=>r.id===gear.rarity)!;return <article key={gear.id} className={`ember-gear-card tier-${tierOf(gear.upgrade)} ${wearing?'equipped':''}`}><GearBadge gear={gear}/><div><small style={{color:rarity.color}}>{rarity.name} · {gear.slot==='weapon'?'อาวุธ':'เกราะ'} {wearing?'· สวมใส่':''}</small><h3>{gear.name} <em>+{gear.upgrade}</em></h3><p>{gear.slot==='weapon'?`พลังอาวุธ ${gearPower(gear)} · สกิลตรงสาย +10%`:`เกราะลดดาเมจ ${(gearPower(gear)*.12).toFixed(1)}`}</p></div><div className="ember-item-actions"><button disabled={wearing} onClick={()=>onChange(current=>({...current,[gear.slot]:gear.id}))}>{wearing?'สวมอยู่':'สวมใส่'}</button><button disabled={!atCamp||gear.upgrade>=20||p.gold<cost.gold||p.stones<cost.stones} onClick={()=>onChange(current=>improveGear(current,gear.id))}>{gear.upgrade===20?'★ MAX':`ตีบวก · ${cost.gold} ◎ / ${cost.stones} ◆`}</button><button disabled={wearing} onClick={()=>onChange(current=>sellGear(current,gear.id))}>ขาย {rarity.sell+gear.upgrade*10} ◎</button></div></article>;})}</div>
      </>}
      {tab==='skills'&&<><div className="ember-panel-note"><b>พาสซีฟคงเหลือ {points} แต้ม</b><span>เลเวลตัวละครเพิ่ม = 1 แต้ม · เปลี่ยนสายฟรีที่แคมป์ · พาสซีฟทุกสายทำงานร่วมกัน</span></div><div className="ember-class-grid">{PATHS.map(c=>{const rank=p.skills[c.id],cost=skillCost(rank);return <article key={c.id} className={`ember-class-card ${p.path===c.id?'active':''}`} style={{'--class-color':c.color} as React.CSSProperties}><div className="ember-class-heading"><span>{c.icon}</span><div><small>{c.role}</small><h3>{c.name}</h3></div><button disabled={!atCamp||p.path===c.id} onClick={()=>onChange(current=>({...current,path:c.id}))}>{p.path===c.id?'สายปัจจุบัน':'เลือกสาย'}</button></div><div className={`ember-skill-rank tier-${tierOf(rank)}`}><b>{c.skill}</b><span>LV.{rank} {rank>=5?'★'.repeat(Math.floor(rank/5)):''}</span></div><p>{c.detail}</p><button className="ember-wide-button" disabled={rank>=20||rank>=level+4||p.gold<cost.gold||p.essence<cost.essence} onClick={()=>onChange(current=>improveSkill(current,c.id))}>{rank>=20?'★ สกิลสูงสุด':rank>=level+4?'เพิ่มเลเวลตัวละครเพื่ออัปต่อ':`อัปสกิล · ${cost.gold} ◎ + ${cost.essence} ✧`}</button><div className="ember-passive"><b>{c.passive} <span>{p.passives[c.id]} / 5</span></b><p>{c.benefit}</p><button disabled={points<=0||p.passives[c.id]>=5} onClick={()=>onChange(current=>improvePassive(current,c.id,score))}>อัปพาสซีฟ · 1 แต้ม</button></div></article>;})}</div></>}
      {tab==='shop'&&<><div className="ember-panel-note"><b>ร้านช่างหม้อ · อาวุธตรงสาย {path.role}</b><span>{atCamp?'รับเหรียญจากการต่อสู้และขายของที่ไม่ใช้':'เดินกลับแคมป์ด้านล่างแผนที่เพื่อซื้อของ'}</span></div><div className="ember-shop-grid">{SHOP.flatMap((item,index)=>(['weapon','armor'] as const).map(slot=><article key={`${slot}-${index}`}><span style={{color:RARITIES.find(r=>r.id===item.rarity)!.color}}>{slot==='weapon'?path.icon:'◈'}</span><h3>{slot==='weapon'?path.name:'เกราะเตาไฟ'}</h3><p>{RARITIES.find(r=>r.id===item.rarity)!.name} · พลัง {RARITIES.find(r=>r.id===item.rarity)!.power}</p><button disabled={!atCamp||p.gold<item.price||p.inventory.length>=40} onClick={()=>{const id=crypto.randomUUID();onChange(current=>buyGear(current,index,slot,id));}}>ซื้อ {item.price} ◎</button></article>))}</div><div className="ember-supplies"><div><b>น้ำซุปอุ่น · 15 ◎</b><small>เติม 3 ขวดฟรีเมื่อพักที่แคมป์ หรือซื้อสำรองสูงสุด 9 ขวด</small></div><button disabled={!atCamp||p.gold<15||p.potions>=9} onClick={()=>onChange(current=>current.gold>=15&&current.potions<9?{...current,gold:current.gold-15,potions:current.potions+1}:current)}>ซื้อ 1 ขวด</button></div></>}
      {tab==='rates'&&<><div className="ember-panel-note"><b>เรตของเกมบนเครื่องนี้</b><span>เงิน หินเวท และผลึกสกิลได้ทุกครั้งที่ชนะ ส่วนอุปกรณ์สุ่มแยกตามค่าด้านล่าง</span></div><label className="ember-rate-row"><span>โอกาสดรอปอุปกรณ์ <b>{rates.equipment}%</b></span><input aria-label="โอกาสดรอปอุปกรณ์" type="range" min="0" max="100" value={rates.equipment} onChange={e=>{setRates({...rates,equipment:Number(e.target.value)});setRateSaved(false);}}/></label><h3 className="ember-rate-heading">สัดส่วนคุณภาพเมื่อดรอปอุปกรณ์</h3>{RARITIES.map((rarity,index)=><label className="ember-rate-row" key={rarity.id}><span style={{color:rarity.color}}>{rarity.name}<b>{total?(rates.weights[index]/total*100).toFixed(1):'0'}%</b></span><input aria-label={`น้ำหนักดรอป${rarity.name}`} type="range" min="0" max="100" value={rates.weights[index]} onChange={e=>{setRates({...rates,weights:rates.weights.map((n,i)=>i===index?Number(e.target.value):n)});setRateSaved(false);}}/></label>)}<p className="ember-rate-help">ค่าปกติ: ดรอปอุปกรณ์ 40% · ธรรมดา 55 / ดีเยี่ยม 27 / แรร์ 13 / อีปิก 4 / ตำนาน 1 · คลังเต็มจะขายของดรอปให้ทันที</p><div className="ember-rate-actions"><button className="ember-gold" disabled={!total} onClick={()=>{onChange(current=>({...current,rates:{equipment:rates.equipment,weights:[...rates.weights]}}));setRateSaved(true);}}>{rateSaved?'✓ บันทึกเรตแล้ว':'บันทึกเรต'}</button><button onClick={()=>{setRates({equipment:40,weights:[55,27,13,4,1]});setRateSaved(false);}}>คืนค่าปกติ</button></div></>}
    </div>
    <footer className="ember-camp-footer"><span>รอบสำรวจ {p.floor} / 20 · ชนะ {p.kills} ครั้ง · บอส {p.bossWins} ครั้ง</span>{atCamp&&p.defeated.includes(2)&&<button disabled={p.floor>=20} onClick={()=>{onChange(current=>advanceExpedition(current,score));onClose();}}>เปิดรอบ {Math.min(20,p.floor+1)} · ศัตรูแกร่งขึ้น / รางวัลเพิ่ม →</button>}</footer>
  </section></div>;
}
